"""
Root schema for the Forecast Agent (Agent 4).

This module defines the main `FinancialForecast` model representing
future financial projections, growth rates, and scenarios.
"""

from datetime import datetime, timezone
from pydantic import BaseModel, Field

# Note: These will be defined in Steps 3 and 4
from .scenario_schema import ScenarioAnalysis
from .assumption_schema import ForecastAssumptions


class MetricForecast(BaseModel):
    """Forecasted values for a single metric across periods."""
    metric_name: str = Field(description="Name of the metric (e.g. revenue, net_profit).")
    projected_values: dict[str, float] = Field(description="Map of period identifier (e.g. '2024') to projected value.")
    confidence_interval: tuple[float, float] | None = Field(default=None, description="Lower and upper bound confidence interval.")
    growth_rate: float | None = Field(default=None, description="Projected CAGR over the forecast horizon.")


class FinancialForecast(BaseModel):
    """
    Root model for all forecast outputs generated by Agent 4.
    """
    metadata: dict[str, str] = Field(
        default_factory=dict,
        description="Forecast metadata: model_used, forecast_horizon, generated_at.",
    )
    
    # Core Forecasts
    revenue_forecast: MetricForecast = Field(description="Revenue projections.")
    expense_forecast: MetricForecast = Field(description="Expense projections.")
    profit_forecast: MetricForecast = Field(description="Profit projections.")
    cash_flow_forecast: MetricForecast = Field(description="Cash flow projections.")
    
    # Additional Requested Forecasts
    operating_margin_forecast: MetricForecast | None = Field(default=None, description="Operating margin projections.")
    ebitda_forecast: MetricForecast | None = Field(default=None, description="EBITDA projections.")
    balance_sheet_projection: dict[str, MetricForecast] = Field(default_factory=dict, description="Projections for key balance sheet items.")
    working_capital_forecast: MetricForecast | None = Field(default=None, description="Working capital projections.")
    free_cash_flow_forecast: MetricForecast | None = Field(default=None, description="Free cash flow projections.")
    
    # Scenarios (Base, Upside, Downside)
    scenarios: dict[str, ScenarioAnalysis] | None = Field(
        default=None, 
        description="Scenario analyses mapping (e.g. 'base_case', 'upside_case', 'downside_case')."
    )
    
    # Configurable Assumptions
    assumptions: ForecastAssumptions | None = Field(
        default=None, 
        description="Underlying assumptions driving the forecast models."
    )
    
    # System fields
    confidence_score: float = Field(default=1.0, ge=0.0, le=1.0, description="Overall confidence in the forecast model.")
    warnings: list[str] = Field(default_factory=list, description="Warnings about missing data, high variance, or impossible projections.")
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), 
        description="UTC timestamp of generation."
    )
